# Generated by Django 5.1.7 on 2025-04-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_team_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
