# Generated by Django 5.1.7 on 2025-04-02 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_billings', to='core.orderbilling', unique=True),
        ),
    ]
