# Generated by Django 5.2 on 2025-06-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
